CREATE TABLE Enderecos (
    Id INT IDENTITY PRIMARY KEY,
    PessoaId INT NOT NULL,
    EnderecoDescricao NVARCHAR(255) NOT NULL,
    Cep NVARCHAR(15) NOT NULL,
    Cidade NVARCHAR(100),
    Estado NVARCHAR(50),
    FOREIGN KEY (PessoaId) REFERENCES Pessoas(Id) ON DELETE NO ACTION
);
